### ISSUE TITLE
Things to ask Preetam Sir

### ISSUE THREAD

**Issue by zeref221** [Bioengineering-Club-2021A/Core-team#1]

**Comment by manaswiproject** [comment]
02/08/21
@zeref221 @iris-byte @Shreeya-Kadam @007divy @unorthodox19112001 @mayankgandhi1307 @amalanbr 
Questions:
1. Which platform are we using?     **(Zoom/ Meet)**
2. Can we do the 2 speakers' idea?  **(Push that till 2nd session & give it a name)**
3. Explain to me like I'm 5 
4. Gmail account and letterhead for the club  **(N/A)**
5. Survey form- will he circulate the form, so this is taken seriously 
6. Show GitHub **(done)**
7. Internship and Startup person (What is the criteria?) **(Coordinate with jeevan sir)**
8. Bio-news ( Jingles/ Conversation) **(YEES)**
9. Will faculties volunteer for research ideas or PhD students for internship/research ideas (in case we don't have anyone) **(YES)**
10. Is Bioclub compulsory for all? **(N/A)**
11. Can we conduct sports tournament, once offline? **(YES)**
12. Procedure and format of Documentation.  **(SIR will GIVE)**
13.  Are we allowed to use logo for Holistic ppts and also for poster? **(YES)**



#add to list

**Comment by Shreeya-Kadam** [comment]
03/08/2021
###  Discuss poster specifications

**Comment by zeref221** [comment]
Is there anything else to ask sir? If no then ill end this issue.

**Comment by zeref221** [comment]
1. Google account & email id
2. Documenter drive
3. Platform?
4. Holistic Event? Date?
5. BEC dates? Alternate Saturday? (How does it fit in our timetable?) Timings & duration?
6. Screen share?
7. When will be meet other faculty for BEC? Cuz we need to co-ordinate
8. Camera on?
9. Logo necessary?
