### ISSUE TITLE
Distribution of task

### ISSUE THREAD

**Issue by zeref221** [Bioengineering-Club-2021A/Core-team#2]
### Task Distribution

SESSION 1

**Comment by manaswiproject** [comment]
PR team tasks: @Shreeya-Kadam 
1. Draft PR message 
2. Make Poster for holistic and Saturday session

#add tasks to this list if needed

**Comment by manaswiproject** [comment]
Creative team tasks: 
@Shreeya-Kadam coordinate with your team

Draft PR message
Make Poster for holistic and Saturday session
#add tasks to this list if needed

**Comment by manaswiproject** [comment]
Creative team tasks:
@Shreeya-Kadam coordinate with your team

1. Make Poster for holistic and Saturday session
2. Co-ordination with photography team and PR
3. Brainstorm for holistic activities

#add tasks to this list if needed

**Comment by manaswiproject** [comment]
PR team tasks:
@Samruddhi-123  coordinate with your team

1. Draft PR message
2. Finalize people for Bio-news, Anchors, Internship (coordinate with faculty) and Project ideas (coordinate with faculty)

#add to list

**Comment by zeref221** [comment]
Session checklist:

☐  Logo for BEC
☐  Internship and startup ka list (Ask Jeevan sir?)
☐  Session date? This Saturday confirmed?
☐  All participants present?
☐  All participants have good internet connection? Are they travelling?
☐  Proof read the contents
☐  Proof read all the script till Thursday
☐  Incase of error, have pre recorded news and project idea
☐  Template from our side, where the participants can just add their slides.
☐  Music while joining and vote of thanks slide at the end (Done by whom?)
☐  Run through with the volunteers on Friday (Debatable)
☐  All the advertisement and messages should be sent to students and faculty latest by Thursday, this includes the messages formed by PR team , social media handling done by the creatives team. (People should know that there is an event happening and the guest presenter arriving)
☐  Which platform? zoom /teams?
☐  Holistic games after the session?
☐  Circulating the survey form after the session 
☐  Introduction of the new committee.
