### ISSUE TITLE
Finalizing the Constitution and the Survey

### ISSUE THREAD

**Issue by KavishaShroff02** [Bioengineering-Club-2021A/Core-team#3]
**Constitution Draft:**
 [https://docs.google.com/document/d/1jabmAFTB6sUcCVaznPBVMDCMsfFc-Sa7x2R_pIdUJTg/edit?usp=sharing] (url)

**Survey Editing form:**
 [https://docs.google.com/forms/d/1Ix0ikalkXK_Rr9C4U2VxKlOvS6JoQy86h8xq8SKEx5c/edit] (url)

// Select the link to open

**Comment by zeref221** [comment]
[https://docs.google.com/document/d/1jabmAFTB6sUcCVaznPBVMDCMsfFc-Sa7x2R_pIdUJTg/edit?usp=sharing]
(Club mandate)

**Comment by zeref221** [comment]
Survey:

-  Make an introduction (What information we need the user to fill in) - Description of the main form
- Two three lines about data transparency and what we can do with this data- in the main description
- Overview of each section (What this section does and what things you must fill)

// Add things which can do into this list
// Report things to @KavishaShroff02

**Comment by amalanbr** [comment]
Constitution:
The responsibilities for the photography team @unorthodox19112001  and sports team @Rahul-Shah12  have to be filled

**Comment by KavishaShroff02** [comment]
@manaswiproject @Shreeya-Kadam just proofread the description of the form

**Comment by unorthodox19112001** [comment]
> Constitution:
> The responsibilities for the photography team @unorthodox19112001 and sports team @Rahul-Shah12 have to be filled

Responsibilities of Photography team:
1. They are responsible for the visual documentation of all the online meetings as well as the events(which includes recording the meeting and taking screenshots as and when needed).
2. They will provide the Monthly recap video. 
3. Same will be done during offline events. Records of events will be photographed and compiled by the team for the social platforms.

**Comment by Rahul-Shah12** [comment]
> Constitution:
> The responsibilities for the photography team @unorthodox19112001 and sports team @Rahul-Shah12 have to be filled

Responsibility of Sports Team:

1. The Male and Female representative of the Sports team will overlook all the sports activities of the Bioengineering Department and coordinate with their Head and Administrative Department about the timings and details.

2. New and engaging ideas which may help the club in conducting sports events. 

3. Arranging small tournaments for development of interpersonal skills.

**Comment by zeref221** [comment]
// Constitution sent on BEC whatsapp group and can be found in Useful_links.
// Survey finalized and would be circulated on Saturday after the session.
