### ISSUE TITLE
Discuss poster specifications

### ISSUE THREAD

**Issue by Shreeya-Kadam** [Bioengineering-Club-2021A/Core-team#4]
03/08/2021

Post meeting with sir, discuss the specifications (eg. BEC logo)

**Comment by zeref221** [comment]
Wouldn't it come under things to ask sir?
@Shreeya-Kadam 
We don't have to ask sir?

**Comment by Shreeya-Kadam** [comment]
@zeref221 
 Depends, we could ask him or we could just decide on our own. Like logo is something that is a must in the posters. But idk if we need something else in it
